### ISSUE TITLE
Make tests faster

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#101]
Tests currently run for over 4 minutes (both locally and in circleci) which is impractical and makes any code changes really tedious. Furthermore, the majority of test cases currently test *both* the javascript code and smart contract implementation. A simple setup for a single test in BookingData takes 2 seconds. I think tests should be as fast as possible to enable rapid iteration.

It should be possible to achieve that with [web3-fake-provider](https://github.com/raineorshine/web3-fake-provider) (which is used in web3 itself as well) that can actually mock every response from smart contracts themselves. If I understand correctly, it should then be possible to drop testrpc altogether.

I've started to fiddle with it here: https://github.com/JirkaChadima/wt-js-libs/tree/features/faster-tests

**Comment by adklempner** [comment]
I think the biggest culprits causing the slow test times are repeated calls to complex setup functions like `help.createWindingTreeEconomy` and `help.generateCompleteHotel` in the mocha hooks `before` and `beforeEach`

This can be mitigated by:
- Identifying where the calls are redundant and removing them from hooks
- Making use of testrpc's `evm_snapshot` and `evm_revert` custom RPC calls to save and restore the test chain's state

I'd prefer these changes over dropping testrpc

**Comment by JirkaChadima** [comment]
Yeah, some constructs are really weird with web3-fake-provider anyway, I'll look into `evm_snapshot`. Support for mocking in tests is really poor in web3 ecosystem.

On the other hand I think that the JS lib should *only* test the JS code and not the underlying contract implementation, because such tests are more of integration tests than unit tests. They have their place, but probably not on a developer's machine.

**Comment by kvbik** [comment]
it can be a difficult decision whether "to mock or not to mock" but i do agree, that JS lib should be testing the JS functionality a and tests of the smart contracts should be in the smart contract repository. but for sure let's find the best course of action together!

**Comment by JirkaChadima** [comment]
I've prepared two very rough POCs:

1) https://github.com/JirkaChadima/wt-js-libs/tree/features/web3-fake-provider - fake provider
2) https://github.com/JirkaChadima/wt-js-libs/tree/features/faster-tests - using snapshot/revert

However, there are issues in both cases:

1 - web3-fake-provider depends on the order of calls and I think it is missing some features that would be useful. It also seems difficult to emulate particular transactions/events.
2 - I am not able to make it work... testrpc (and even the newest ganache-cli) are dying on a transaction call after `evm_revert` and I am not sure why. It might be somehow connected to gas as the transaction/gas estimation is reverted every time. What is more, the snapshot/revert combo is helpful only in a few places, so the performance gain is in tens of percents, not in orders of magnitude.

I think that with a decent refactoring, it should be possible to keep both options (fast tests, testrpc) in place. It would require moving all calls related to Web3 to a separate class/library and then it should be possible to either mock all calls or relay them to testrpc (or even testnet?).

For me as a newcomer, it is really hard to wrap my head around all the concepts that this library deals with, but I believe it is possible to provide a sleeker and more user-friendly API. Unfortunately, slow tests really don't help and it seems that there is so much going on that even if I break something, I'm oftentimes not sure why. Also it seems to me that all components in the library are very tightly coupled which might make future expanding really hard.

@adklempner, is there some huge benefit of keeping testrpc around here that I am not seeing? What do you think about separating all Web3 calls apart?

**Comment by adklempner** [comment]
I tried getting the snapshot/revert tests on your branch working and had no luck either :/
Also, it looks like `evm_revert` [deletes the snapshot after reverting](https://github.com/trufflesuite/ganache-cli/issues/138), so this feature might not be of much use to us after all.

I'm still trying to wrap my head around how the fake provider works, and there doesn't seem to be much documentation on it. What happens when you call `provider.injectResult({data: encodedParams})`? Does this tell it to return that data next time a call matches those param types?

With regards to separating Web3 calls, most of what the library does is build and make these calls. If we separate them there wouldn't be much left 😛 (unless I'm misunderstanding what you're suggesting)

**Comment by JirkaChadima** [comment]
> What happens when you call provider.injectResult({data: encodedParams})? Does this tell it to return that data next time a call matches those param types?

That's exactly the issue. It internally creates a simple queue of responses and every time anything asks for a response, the first unused result is returned. You don't really have that much control of what is happening. It's unfortunately a long way from being really flexible and usable. But I think it's a viable concept and it should be possible to improve it's behaviour.

> With regards to separating Web3 calls, most of what the library does is build and make these calls. If we separate them there wouldn't be much left stuck_out_tongue (unless I'm misunderstanding what you're suggesting)

I mean a separation only on a design level in javascript. I've tried to start some groundwork (see
https://github.com/JirkaChadima/wt-js-libs/commit/a7eeb6cbf1c6b32dde9424977bc91cb2c0015b6c) and there is still a lot of issues, but I think it should be possible to configure what kind of implementation of web3 should be used - and in the tests we might be able to use just some simple in-memory mock. As a first step, I'm trying to rewrite the code in a way that it always uses an injected instance of web3.

**Comment by adklempner** [comment]
We might be better off using a mocking library like [sinonjs](http://sinonjs.org) how another Ethereum project with libraries, machinomy does in [their tests](https://github.com/machinomy/machinomy/blob/master/test/payment_manager.test.ts)

**Comment by JirkaChadima** [comment]
That’s exactly what I have in mind. We just have to restructure the library a little bit for this approach to work as expected.

**Comment by JirkaChadima** [comment]
Another approach worth exploring might be the use of https://github.com/mfncooper/mockery which can replace a `require` call with your own mock

**Comment by JirkaChadima** [comment]
@adklempner Check this out: https://github.com/JirkaChadima/wt-js-libs/blob/features/refactoring/test/BookingData.js#L73

I had to do a lot of work under the hood (mainly reorganizing code and how things are passed around) and slightly changed some interfaces / dropped some code along the way (and might actually change more), but we have a first completely mocked test. On my machine it's `6s` against `22ms` (on the two functioning mocked tests). I'd say that's pretty good!

Of course to be able to seamlessly switch from testrpc to mocks will require another decent amount of work, but that should be pretty easy once we are able to mock things at will.

What do you think? I'm going to slowly push this forward just to see if it's a viable concept (and I beleive it is) for other tests (such as events and transactions).

**Comment by adklempner** [comment]
I think that's a great approach!

An important thing to consider when mocking results of web3/contract calls is that web3 returns a `BigNumber` object for number values. For example, the function `Unit.defaultPrice()` is a getter for `uint256 defaultPrice`, and web3js returns  types of `uint256` as a `BigNumber` object. It's important to in this case to run tests on the `BigNumber` object, as the behavior can differ from Javascript's `Number`.

**Comment by JirkaChadima** [comment]
@adklempner Could you check out #109? There are now both test suites:

- The fast one is run against a sinon mock and against live code from `libs`
- The original one is run against testrpc, and a built library from `dist` folder

**Comment by JirkaChadima** [comment]
Closed by #109
