### ISSUE TITLE
Proposal: Basic hotel data format

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#125]
The goal of this issue is to reach a consensus on a shape of descriptive hotel data. Inventory (rooms), pricing, availability and booking are *not* part of this issue. After we create a data definition, we will have to formalize it (maybe swagger/openapi descriptor would work) and implement it in this library as additional hotel data and also implement it in the wt-nodejs-api endpoints. It might also make sense to separate the code handling on-chain and off-chain data to multiple methods to make the library more readable and data flow more transparent. The current approach might not be flexible enough when we let our users choose the way of storing their data.

I tried to compare the following standards/specifications and select a minimal necessary and common subset that we could start with. This will also enable us to write adapters for different providers in the future (such as OTA <-> WT) with simple data mapping.

- Our original on-chain data storage [Hotel.sol](https://github.com/windingtree/wt-contracts/blob/v0.1.0/contracts/hotel/Hotel.sol)
- [RoomRanger](https://roomranger.com/) - not public right now
- Expedia's [Property API](https://expediaconnectivity.com/apis/product-management/property-api-contact-expedia-before-adopting-/api-definition.html) and [Product API](https://expediaconnectivity.com/apis/product-management/product-api/quick-start.html)
- [HTNG](http://www.htng.org/?page=technical_specs)
- [SynXis/Sabre](https://developer.sabre.com/sabre_hospitality/apis/soap_apis/hotel/channel_connect/ari)
- [siteminder](https://siteminder.atlassian.net/wiki/spaces/PMSXCHANGEV2/overview)
- [OXI](https://docs.oracle.com/cd/E91116_01/docs/User%20Manual.pdf), https://docs.oracle.com/cd/E91116_01/docs/Communication%20Vendor%20Specification.pdf

The very incomplete comparison and data mapping can be seen on https://docs.google.com/spreadsheets/d/1dqQVvF7IIkurIMSMENbB04Fe2HOxbvI9DgYxnhPoGv8/edit?usp=sharing

# Example data

```
{
  "name": "Example hotel",
  "description": "Luxurious hotel near the city center",
  "contacts": {
    "general": {
      "email": "hotelmanager@example.com",
      "phone": "555-555",
      "url": "https://example.com",
      "ethereum": "0xDAD697274F95F909ad12437C516626d65263Ce47" // or windingtree.eth
    }
  },
  "address": {
    "line1": "Main Street",
    "line2": "",
    "zip": "12345",
    "city": "Capitol city",
    "state": "New York",
    "country": "US"
  },
  "location": {
    "latitude": "52.323475",
    "longitude": "2.665040"
  },
  "timezone": "America/New_York",
  "currency": "USD",
  "images": ["http://example.com/picture-1.png", "http://example.com/picture-2.png"],
  "amenities": ["hot tub", "TV"],
  "created_at": "ISO8601 timestamp",
  "updated_at": "ISO8601 timestamp"
}
```

Please, have a look at it @augustol, @czervenka, @kvbik, @MatiasOS

**Comment by AugustoL** [comment]
@JirkaChadima great, I think is enough for general hotel information. Maybe add one/two more field for the ETH address or ENS of the owner and the hotel smart contract address? Since this file can be distributed off chain it can be an entry point to get on chain information about the hotel.

**Comment by JirkaChadima** [comment]
Owner is straightforward, I'll add it to `contacts` section.

Hotel address isn't that simple - it's a chicken and egg problem. You need to know the data and its url to create a hotel on-chain. But you don't know the hotel ETH address before deploying it - so you can't write it to off-chain data. It's probably fine with storages that don't use content-based addressing to just update the off-chain data after the contract is deployed, but I don't think it's feasible for IPFS or Swarm storage.

**Comment by JirkaChadima** [comment]
I'm going to define this as part of #127 since it heavily depends on the off-chain data storage.

**Comment by JirkaChadima** [comment]
Please point further discussion to https://github.com/windingtree/wiki/issues/22 if necessary
