### ISSUE TITLE
Make underscore naming convention of private methods and properties consistent

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#133]
In `proposal/next` branch, there are some properties and methods declared private by an underscore notation. However, the naming is inconsistent, sometimes only one (`_`) is used and sometimes two (`__`) are used.

There's an interesting discussion [on React](https://github.com/airbnb/javascript/issues/1024) about using underscores at all. Apparently there are strong positions on both sides and even though I personally respect the convention of not touching/using anything that starts with an underscore, I totally get the counter-argument, that many people actually ignore it.

Since there are valid uses case for underscore prefixed variables (for example when we're using setters/getters, see #136), we'll just need to make the naming consistent.

~~So, let's ditch the whole underscore thing and use something like [no-underscore-dangle](https://eslint.org/docs/rules/no-underscore-dangle) to enforce it.~~

**Comment by hynek-urban** [comment]
@JirkaChadima Are we sure we want to do this? I like underscores to denote just locally used variables a lot :) :-1 as far as I'm concerned.

**Comment by JirkaChadima** [comment]
@hynek-urban Sure, I don't really care :-) I'll restate this issue to just make it consistent.
