### ISSUE TITLE
Recursive toPlainObject

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#134]
In `proposal/next` branch, we have a `toPlainObject` method on a hotel. This spits out the on-chain stored hotel data. But it does ignore the related off-chain stored data. It would be nice to have a version of this method that would actually traverse the off-chain stored data and spit them out as well.

This means implementing some sort of recursive flatten method in a `StoragePointer` and extending the `toPlainObject` method to call the flattening method on `dataIndex` and/or other child properties. It makes sense to have a `depth` argument as well, since the data files might be linked recursively.

**Comment by beogip** [comment]
@JirkaChadima I could check this issue if you like. I'm not familiarized with the project, so correct me if I'm wrong. StoragePointer has off-chain data stored in the property `contents`, this data could be an object with `n depth`. 
What type of data stores that property? Could you give me an example of input and output data, please?

**Comment by JirkaChadima** [comment]
@beogip I'll try to explain how it behaves, but it's a little abstract, so feel free to hit me up with more questions.

`StoragePointer` basically represents a document that is stored off-chain. In that document, we expect a  plain JSON object with any depth. That's the basic use case.

However, as a user of `StoragePointer`, you can define that some properties on that document (see [this](https://github.com/windingtree/wt-js-libs/blob/proposal/next/src/data-model/on-chain-hotel.js#L97) or [this](https://github.com/windingtree/wt-js-libs/blob/proposal/next/src/data-model/on-chain-hotel.js#L97) or the tests - hopefully :-)) are representing another document stored off-chain. When this happens, `StoragePointer` [treats](https://github.com/windingtree/wt-js-libs/blob/proposal/next/src/storage-pointer.js#L142) this property as another `StoragePointer` - that's where the recursion sets in.

So the motivation behind this issue is this: A `StoragePointer` should be able to return a plain JSON object. The depth attribute should say, how many nested `StoragePointer`s should be converted from a url to a plain JSON object as well. The depth attribute should not affect any data that is not `StoragePointer`. The reasoning is that getting any off-chain document is expensive, so you should be able to control the *slowness* of this method.

**Comment by JirkaChadima** [comment]
I'm going to take care of this, it will clear up the whole interface a lot.
