### ISSUE TITLE
Enforce manager and url rules consistently

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#135]
We prevent modification of manager/url data stored on-chain at certain states. However, this logic is only enforced in `setLocalData` method, but you can modify manager and url values directly by `hotel.url = 'something';`

We should be consistent in enforcing these rules to prevent accidental data inconsistency. The truth about when the data is modifiable is now in `setLocalData` method.

**Comment by beogip** [comment]
@JirkaChadima I'll glad to help with this issue. Do you have a specific URL format?

**Comment by JirkaChadima** [comment]
Closed by #136
