### ISSUE TITLE
Check UnhandledPromiseRejectionWarning in bindProperties

### ISSUE THREAD

**Issue by beogip** [windingtree/wt-js-libs#139]
Running the tests I'm getting this warning:
<img width="873" alt="screen shot 2018-06-15 at 9 17 22 pm" src="https://user-images.githubusercontent.com/1965274/41494048-98ea2856-70e4-11e8-8819-9fb8c426c7a8.png">
we should check if this unhandled rejection could generate an error using the lib

**Comment by JirkaChadima** [comment]
It's not happening on `proposal/next` branch (check Travis if you don't believe me), it seems like something itntroduced with #136

**Comment by JirkaChadima** [comment]
Found it. It's a legit error that is fired [here](https://github.com/windingtree/wt-js-libs/blob/proposal/next/src/remotely-backed-dataset.js#L184). I'll fix it. I don't how, but I'll fix it :-)
