### ISSUE TITLE
Cache repeatedly requested WTIndex instances

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-js-libs#165]
We can pretty easily cache all requested instances of WTIndex by its address. It will save some resources.

**Comment by hynek-urban** [comment]
@JirkaChadima I thought about this in the context of write API as well, but how would you deal with cache invalidation in this case? I mean, the index will supposedly be updated on a regular basis...

**Comment by JirkaChadima** [comment]
I didn't mean to cache data, only the instances in the factory method.

**Comment by hynek-urban** [comment]
@JirkaChadima Right, sorry, I misunderstood this.
