### ISSUE TITLE
Add a CompleteHotel deployer

### ISSUE THREAD

**Issue by cgewecke** [windingtree/wt-js-libs#31]
@kvbik is getting raw data from a partner. It might be to nice have a method that could take a `json` representation of a hotel and deploy it to the chain, estimating the cost, detecting errors before deployment, etc. 

Useful for validation work but also a good tool to have in the api generally - end users might find it convenient and at some point it could be made 'smart' about deploying large Hotels in tranches over a sequence of blocks.

**Comment by MatiasOS** [comment]
Currently, a complete hotel is like 
```
{
  name: 'Test Hotel',
  description: 'Test Hotel desccription',
  manager: '0x79f7025433b625cFf76eC42E2466042469323A73',
  lineOne: '',
  lineTwo: '',
  zip: '',
  country: '',
  created: 5,
  timezone: 2,
  latitude: '-180.000000',
  longitude: '-90.000000',
  waitConfirmation: false,
  images: ['image.url0', 'image.url1'],
  unitTypeNames: [ 'TYPE_000' ],
  unitTypes:{
    TYPE_000:{
      address: '0xc6111AD59674135b6c8bf22DB1F9Ec0F45a0F67D',
      amenities: [22, 33],
      info: {
        description: null,
        minGuests: null,
        maxGuests: null,
        price: null
      },
      images: ['image.url2', 'image.url3']
    }
  },
  units:{
    '0x147a9278DfD8e3abb6D8b7D66942D7c8A6F600C9':{
      active: true,
      unitType: 'TYPE_000',
      currencyCode: null,
      defaultPrice: '78.00',
      defaultLifPrice: 2
    }
  },
  unitAddresses: [ '0x147a9278DfD8e3abb6D8b7D66942D7c8A6F600C9' ]
}
```
To get this done, we must follow the next steps ( items at same level can be done in parallel)
- Create Hotel
  - Set require confirmation
  - Change Hotel Info
  - Change hotel address
  - Change hotel location
  - Add Images
  - Add unit types
     - Edit Unit type
     - Add images for unit type
     - add amenities
     - add units
       - set currency code for unit
       - set default price for unit
       - set default Lif price for unit
       - set unit active
