### ISSUE TITLE
Topic: web3 1.0 quirks

### ISSUE THREAD

**Issue by cgewecke** [windingtree/wt-js-libs#38]
Opening this as a reference for anyone new to web3 1.0 and will add to it periodically.

**Comment by cgewecke** [comment]
All new contract instances have their provider set to `localhost:8545` regardless of the web3 objects 'actual' provider. When getting an instance that's deployed on a remote client like infura's ropsten, you must explicitly:
```
contract.setProvider(web3.currentProvider);
```
(ProTip courtesy @adklempner).

**Comment by AugustoL** [comment]
Closing because web3js 1.0 was successfully integrated and works fine now.
