### ISSUE TITLE
Validate all lib method call parameters 

### ISSUE THREAD

**Issue by cgewecke** [windingtree/wt-js-libs#44]
We could bring a package like [this](https://www.npmjs.com/package/node-validator) in and extend it to use the web3 utils checkers like isAddress. Ideally it should have a minimalist presence at the top of every method, like a single call that takes an object with type description mapped to variable and returns a Boolean or something.

**Comment by MatiasOS** [comment]
What do you think of use [Joi](https://github.com/hapijs/joi) as validator? I was using it for about a year and practically had no problems
