### ISSUE TITLE
HotelManager: web3 provider for contracts different from constructor web3

### ISSUE THREAD

**Issue by adklempner** [windingtree/wt-js-libs#52]
When creating a HotelManager, I pass it an instance of web3 with the provider set to ropsten.infura

The contract instances (for example, WTIndex) created by the HotelManager all end up having a web3 provider of localhost:8545

**Comment by cgewecke** [comment]
@adklempner Do you know where is this bug originating?

By design the class is supposed to pass constructor arg instance around / only invoke it by dereference.

Even if there's a globalized `web3` we should have control.

**Comment by adklempner** [comment]
I believe it's originating here: [https://github.com/windingtree/wt-js-libs/blob/master/libs/util/misc.js#L147](https://github.com/windingtree/wt-js-libs/blob/master/libs/util/misc.js#L147)

The`currentProvider` of that contract object is set to `localhost:8545`, even though the `web3` arg has the provider set to ropsten

**Comment by cgewecke** [comment]
That's insane. Haha :) Can you dereference directly off the `context` and see if that makes a difference?

**Comment by adklempner** [comment]
It did not.
Adding `contract.setProvider(web3.currentProvider);` seemed to do the trick

**Comment by AugustoL** [comment]
Crazy, we should add the issue in web3.js

**Comment by cgewecke** [comment]
Interesting! I mean it sort of makes sense. . . . nice work. Are you going to open a PR? If you do will you get rid of that unecessary`const` assignment and just use context? And also here just below:
```
async function fundAccount(from, to, amount, web3){
  return web3.eth.sendTransaction({
    from: from,
    to: to,
    value: web3.utils.toWei(amount, 'ether')
  });
};
```
put an underscore before all the`web3s` like a magical thinking paranoiac? Thanks!

**Comment by cgewecke** [comment]
Oh idk - I mean they assume a local client. They're purists?

**Comment by cgewecke** [comment]
It definitely should be a note in the docs at the very least though.

**Comment by AugustoL** [comment]
@cgewecke yes, weird, we should create an issue tomorrow.

**Comment by cgewecke** [comment]
@adklempner I'm going to patch in your fix with a new build.
