### ISSUE TITLE
Use interfaces instead of full contracts ABI in misc.js

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-js-libs#53]
We should use the interfaces instead of the full contract ABI, we want to follow the interface standard and the methods that are only available there, It will also make the builds smaller.

**Comment by cgewecke** [comment]
The interface binary looks like this:
```javascript
"unlinked_binary": "0x",
```
We need the full binary for Units and UnitTypes to deploy them. Their ABI's are identical and have identical weight.

Is it possible that standardization could be achieved by doing what @adklempner suggests in [issue 145 at wt-contracts](https://github.com/windingtree/wt-contracts/issues/145) where they are just inherited abstractions? Plus some kind of package management versioning through `epm` or `npm`? 

If I'm completely misunderstanding this issue please let me know, I'm not sure what to do here.

**Comment by JirkaChadima** [comment]
The idea behind this issue was implemented in #163, closing this.
