### ISSUE TITLE
Add generateHash function in utils

### ISSUE THREAD

**Issue by AugustoL** [windingtree/wt-js-libs#83]
We need a function to generate the transaction hash that is going to be used when creating a tx to interact or deploy a contract. The function will receive address of the contract, the type of contract, the function to execute and the arguments. It should return the generated tx hash.

Why? Right now you have to wait the tx to be mined and you can only use the lib in a asynchronous way, for the API we want to return the hash of the tx to be executed right away and not wait for the tx to be mined to give a response.

**Comment by adklempner** [comment]
Resolved using callback functions in #85
